# Generated by Django 5.0.6 on 2024-06-23 22:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50, verbose_name='NAME')),
                ('STUSPS', models.CharField(max_length=50, verbose_name='STUSPS')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='MULTIPOLYGON')),
            ],
        ),
    ]
